# Generated by Django 5.1.1 on 2024-09-16 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="website",
            old_name="domain_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="website",
            name="created_at",
        ),
        migrations.AddField(
            model_name="website",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="domain",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="website",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
